FROM public.ecr.aws/lambda/python:3.11

# Install necessary packages
RUN yum update -y && yum install -y poppler-utils

# Copy application code
COPY local_test.py .
COPY pdf2png.py .
COPY requirements.txt.local .
COPY your.pdf .

# Install Python dependencies
RUN pip3.11 install --no-cache-dir -r requirements.txt.local

# Install bash
RUN yum install -y bash
